# Generated by Django 2.2.12 on 2020-10-20 13:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tweet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=1000)),
                ('owner', models.CharField(max_length=1000)),
                ('date', models.DateTimeField(default=datetime.datetime(2020, 10, 20, 13, 57, 13, 743377))),
            ],
        ),
    ]
