# Generated by Django 2.2.12 on 2020-10-20 13:59

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20201020_1358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweet',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 20, 13, 59, 32, 874368, tzinfo=utc)),
        ),
    ]
