# Generated by Django 3.1.2 on 2020-10-21 19:48

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20201020_1359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweet',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 21, 19, 48, 54, 889281, tzinfo=utc)),
        ),
    ]
