# Generated by Django 3.1.2 on 2020-10-21 20:03

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20201021_1948'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweet',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 21, 20, 3, 23, 242873, tzinfo=utc)),
        ),
    ]
