# Generated by Django 3.1.2 on 2020-10-21 20:05

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20201021_2003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweet',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 21, 20, 5, 32, 506512, tzinfo=utc)),
        ),
    ]
